### ISSUE TITLE
User can see weather in header based on zip code

### ISSUE THREAD

**Issue by marissalortega** [marissalortega/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the weather in header of page based on zip code.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can see location-based weather forecast in the header.  Weather will include the city name, the high and low temperature, and an icon representing sunny, cloudy, windy, etc.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1283" alt="Screen Shot 2022-06-09 at 7 24 28 PM" src="https://user-images.githubusercontent.com/90414477/172978588-e8c403af-1ec9-4208-84b9-0980046c9f74.png">
<img width="187" alt="Screen Shot 2022-06-09 at 7 27 16 PM" src="https://user-images.githubusercontent.com/90414477/172978620-ffa990fb-2e61-4780-a1bd-0a978b322cec.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add code to`index.html` to create a `head` and `body` elements that match the desktop and mobile wireframes.
- [x] Make sure that API and JS display correctly in the browser `header`.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Add text to the browser that tells the user if no posts have been added to the feed.
- [x] Add a `button` that allows the user to add a post to the feed.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
