### ISSUE TITLE
User can post class updates to feed.

### ISSUE THREAD

**Issue by marissalortega** [marissalortega/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add class and school updates that will populate a feed.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the "add" button from the feed page to reveal a form that they fill out to provide updates to the class and/or school.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90414477/186299550-6a2f7ff6-d17b-42c1-883e-249bdd854edc.png)
![image](https://user-images.githubusercontent.com/90414477/186299623-64c96ef7-cecf-47ae-8ab3-102999c981aa.png)
![image](https://user-images.githubusercontent.com/90414477/186299739-d44f9ab8-4abc-4f76-9f9f-98ba2af119f3.png)
![image](https://user-images.githubusercontent.com/90414477/186299768-2708849c-0838-42f3-bf5b-78fc1cf92e57.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Build a form in the HTML.
- [ ] Write CSS for desktop.
- [ ] Add CSS media queries for mobile.
- [ ] Add JavaScript to make the form appear when the "add" button is clicked.
- [ ] Add Javascript to make the form disappear and populate the feed with the form entries when the submit button is clicked.
- [ ] Form entries should be arranged with the most recent entry on the top.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
